# modules:
#   - module_type: langchain_parse
#     parse_method: json
#     jq_schema: |
#       {
#         "messages": [
#           { "subject": ".data[].subject" },
#           { "title": ".data[].title" },
#           { "content": ".data[].content" }
#         ]
#       }